(define (f a #!optional b (c 3))
  (string-append (number->string a) "/"
                 (if b (number->string b) "F") "/"
                 (number->string c)))
(define (g a #!optional (b (+ a 1))) (+ a b))
(define (h a #!rest r) (+ a (length r)))
(define (k a #!key x (y (* a 2)))
  (string-append (number->string a) "/"
                 (if x (number->string x) "F") "/"
                 (number->string y)))
(define (m #!rest r #!key q)
  (string-append (number->string (length r)) "/"
                 (if q (number->string q) "F")))
(define lam (lambda (p #!optional (n (* p 10))) (+ p n)))
(define (allrest #!rest r)
  (if (null? r) "empty" (number->string (length r))))
(element doc (make display-group (process-children)))
(element title (make paragraph
  (literal (f 1))
  (literal " ")
  (literal (f 1 2))
  (literal " ")
  (literal (f 1 2 4))
  (literal " ")
  (literal (number->string (g 5)))
  (literal " ")
  (literal (number->string (g 5 10)))
  (literal " ")
  (literal (allrest))
  (literal " ")
  (literal (allrest 9 8 7))))
(element p (make paragraph
  (literal (number->string (h 1)))
  (literal " ")
  (literal (number->string (h 1 2 3 4)))
  (literal " ")
  (literal (k 3))
  (literal " ")
  (literal (k 3 x: 7))
  (literal " ")
  (literal (k 3 y: 1 x: 2))
  (literal " ")
  (literal (k 3 x: 5 x: 9))
  (literal " ")
  (literal (m))
  (literal " ")
  (literal (m q: 5))
  (literal " ")
  (literal (number->string (lam 2)))
  (literal " ")
  (literal (number->string (lam 2 3)))))
(element em (make sequence (process-children)))
