(element doc (make display-group
  (process-children)))
(element title (make paragraph
  (literal (format-number 1 "1"))
  (literal " ")
  (literal (format-number 42 "001"))
  (literal " ")
  (literal (format-number -5 "0001"))
  (literal " ")
  (literal (format-number 0 "1"))))
(element p (make paragraph
  (literal (format-number 1 "a"))
  (literal " ")
  (literal (format-number 26 "a"))
  (literal " ")
  (literal (format-number 27 "a"))
  (literal " ")
  (literal (format-number 702 "a"))
  (literal " ")
  (literal (format-number -3 "A"))
  (literal " ")
  (literal (format-number 0 "a"))
  (literal " ")
  (literal (format-number 1998 "i"))
  (literal " ")
  (literal (format-number 4 "I"))
  (literal " ")
  (literal (format-number 9 "i"))
  (literal " ")
  (literal (format-number 444 "I"))
  (literal " ")
  (literal (format-number 3999 "i"))
  (literal " ")
  (literal (format-number 5001 "i"))
  (literal " ")
  (literal (format-number -12 "i"))
  (literal " ")
  (literal (format-number-list '(1 2 3) "1" "."))
  (literal " ")
  (literal (format-number-list '(4 5) '("A" "i") '("-")))
  (literal " ")
  (literal (format-number-list '() "1" "."))
  (literal " ")
  (literal (format-number-list '(7 8) '("01" "a") "+"))))
(element em (make sequence
  (process-children)))
