<!NOTATION SGML PUBLIC "-//ISO 8879:1986//NOTATION Standard Generalized Markup
    Language//EN">

<?IS10744 ArcBase oj>
<!NOTATION oj PUBLIC "-//OpenJade Project//NOTATION AFDR ARCBASE oj Architecture//EN">
<!ATTLIST #NOTATION oj
    ArcDTD CDATA #FIXED "ojdtd">
<!ENTITY ojdtd SYSTEM "af-16-ojmeta.dtd" CDATA SGML>
<!ELEMENT open     - o (stanza+)>
<!ATTLIST open
  oj NMTOKEN #FIXED "oj">
<!ELEMENT stanza   - o (verse+)>
<!ATTLIST stanza
  oj NMTOKEN #FIXED "s">
<!ELEMENT verse    - o (#PCDATA)>
<!ATTLIST verse
  n CDATA #REQUIRED
  oj NMTOKEN #FIXED "v">
