<!NOTATION SGML PUBLIC "-//ISO 8879:1986//NOTATION Standard Generalized Markup
    Language//EN">

<?IS10744 ArcBase open>
<!NOTATION open PUBLIC "-//OpenJade Project//NOTATION AFDR ARCBASE open Architecture//EN">
<!ATTLIST #NOTATION open
    ArcDTD CDATA #FIXED "opendtd">
<!ENTITY opendtd SYSTEM "af-meta-14.dtd" CDATA SGML>

<!ELEMENT doc - o (s+,n)>
<!ATTLIST doc
  open NMTOKEN   #FIXED "open">
<!ELEMENT s   - o (v+)>
<!ELEMENT v   - o (#PCDATA)>
<!ATTLIST v
  n ID        #REQUIRED>
<!ELEMENT n   - o (i+)>
<!ATTLIST n
  open NMTOKEN   #FIXED "notes">
<!ELEMENT i   - o (#PCDATA)>
<!ATTLIST i
  r IDREF        #REQUIRED>
