<!NOTATION SGML PUBLIC "-//ISO 8879:1986//NOTATION Standard Generalized Markup
    Language//EN">

<?IS10744 ArcBase open>
<!NOTATION open PUBLIC "-//OpenJade Project//NOTATION AFDR ARCBASE open Architecture//EN">
<!ATTLIST #NOTATION open
    ArcDTD CDATA #FIXED "opendtd">
<!ENTITY opendtd SYSTEM "af-meta-29.dtd" CDATA SGML>
<!ENTITY text-ent "an SGML text entity, not data">
<!ELEMENT doc - o (s+)>
<!ATTLIST doc
  open NMTOKEN #FIXED "open">
<!ELEMENT s   - o (#PCDATA)>
<!ATTLIST s
  open NMTOKEN #FIXED "stanza"
  content CDATA #IMPLIED>
