<!NOTATION SGML PUBLIC "-//ISO 8879:1986//NOTATION Standard Generalized Markup
    Language//EN">

<?IS10744 ArcBase open>
<!NOTATION open PUBLIC "-//OpenJade Project//NOTATION AFDR ARCBASE open Architecture//EN">
<!ATTLIST #NOTATION open
    ArcDTD CDATA #FIXED "opendtd"
    ArcDataF NAME #FIXED opendata>
<!ENTITY opendtd SYSTEM "af-meta-27.dtd" CDATA SGML>
<!ENTITY body-ent CDATA "some replacement text">
<!ENTITY pic-ent SYSTEM "pic.gif" CDATA SGML>
<!ENTITY pic2-ent SYSTEM "pic2.gif" CDATA SGML>
<!ELEMENT doc - o (s+)>
<!ATTLIST doc
  open NMTOKEN #FIXED "open">
<!ELEMENT s   - o (#PCDATA)>
<!ATTLIST s
  open NMTOKEN #FIXED "stanza"
  content ENTITY #IMPLIED
  pics ENTITIES #IMPLIED>
