#!/usr/bin/env python3
# tools/dssslgen.py [--check]
#
# packages/dazzle/0.1.0/dsssl/ holds what the engine needs beside a stylesheet:
# the DSSSL prolog (builtins.dsl) and what reads a stylesheet as the SGML
# document it is (catalog and three DTDs). This writes them into
# packages/dazzle/0.1.0/dazzle/DssslData.scaly as strings, so that the program
# carries them and runs from any directory. The files stay the source: edit
# them, then run this. --check compares and writes nothing.
import hashlib, os, sys
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "packages/dazzle/0.1.0/dsssl")
OUT = os.path.join(ROOT, "packages/dazzle/0.1.0/dazzle/DssslData.scaly")
NAMES = ["builtins.dsl", "catalog", "dsssl.dtd", "fot.dtd", "style-sheet.dtd"]

def literal(text):
    out = []
    for ch in text:
        if ch == "\\": out.append("\\\\")
        elif ch == '"': out.append('\\"')
        elif ch == "`": out.append("\\`")
        elif ch == "\n": out.append("\\n")
        elif ch == "\t": out.append("\\t")
        elif ch == "\r": out.append("\\r")
        elif " " <= ch <= "~": out.append(ch)
        else: sys.exit("dssslgen: %r is not ASCII" % ch)
    return "".join(out)

texts = [open(os.path.join(SRC, n), encoding="ascii").read() for n in NAMES]
stamp = hashlib.sha256("\0".join(texts).encode()).hexdigest()[:16]
lines = [
    "; GENERATED by tools/dssslgen.py from packages/dazzle/0.1.0/dsssl/ -- edit",
    "; the files there, then run the generator; tests/dazzle/cli checks it.",
    ";",
    "; What the engine needs beside a stylesheet, carried in the program: the",
    "; DSSSL prolog and the catalog with the three DTDs that read a stylesheet.",
    "",
    "; the number of files, the name and the text of the i-th (a function,",
    "; no constant: a program under programs/ counts as its package's own",
    "; module to the planner, and a constant of a module planned after it is",
    "; not visible there)",
    "function dsssl_data_count() returns int",
    "    %d" % len(NAMES),
    "",
    "; what the texts are a function of: the directory they are laid into is",
    "; named after it (programs/dazzle.scaly dsssl_directory#)",
    "function dsssl_data_stamp() returns String",
    '    "%s"' % stamp,
    "",
    "function dsssl_data_name(i: int) returns String",
    "{",
]
for i, n in enumerate(NAMES):
    lines += ["    if i = %d" % i, '        return "%s"' % n]
lines += ['    ""', "}", "", "function dsssl_data_text(i: int) returns String", "{"]
for i, t in enumerate(texts):
    lines += ["    if i = %d" % i, '        return "%s"' % literal(t)]
lines += ['    ""', "}", ""]
new = "\n".join(lines)
if "--check" in sys.argv:
    old = open(OUT, encoding="ascii").read() if os.path.exists(OUT) else ""
    if old != new:
        sys.exit("dssslgen: packages/dazzle/0.1.0/dazzle/DssslData.scaly is not what the files in dsssl/ give -- run tools/dssslgen.py")
    print("dssslgen: current")
else:
    open(OUT, "w", encoding="ascii").write(new)
    print("dssslgen: wrote", os.path.relpath(OUT, ROOT), "stamp", stamp)
