/* config.h — generated by CMake from cmake/config.h.cmake */

#ifndef config_INCLUDED
#define config_INCLUDED 1

/* ======================================================================
 * Feature detection (probed by CMake)
 * ====================================================================== */

#cmakedefine HAVE_BOOL
#cmakedefine HAVE_TYPENAME
#cmakedefine HAVE_MUTABLE
#cmakedefine HAVE_NAMESPACES
#cmakedefine HAVE_NAMESPACE_STD
#cmakedefine HAVE_NEW_FOR_SCOPING
#cmakedefine HAVE_DYNAMIC_CAST
#cmakedefine HAVE_INSTANTIATIONS
#cmakedefine HAVE_PLACEMENT_OPERATOR_NEW
#cmakedefine HAVE_PLACEMENT_OPERATOR_DELETE
#cmakedefine HAVE_NEW
#cmakedefine HAVE_CASSERT
#cmakedefine HAVE_SETLOCALE
#cmakedefine HAVE_GETTEXT
#cmakedefine HAVE_ICONV
#cmakedefine HAVE_WCHAR_T
#cmakedefine HAVE_WCSLEN
#cmakedefine HAVE_ST_BLKSIZE
#cmakedefine HAVE_UNISTD_H
#cmakedefine HAVE_IO_H
#cmakedefine HAVE_OSFCN_H
#cmakedefine HAVE_LIMITS_H
#cmakedefine HAVE_STRERROR
#cmakedefine HAVE_MEMMOVE
#cmakedefine HAVE_MEMCMP
#cmakedefine HAVE_LIBPTHREAD
#cmakedefine HAVE_LIBTHREADS

#cmakedefine ENABLE_NLS

#define SIZEOF_BOOL @SIZEOF_BOOL@
#define SIZEOF_WCHAR_T @SIZEOF_WCHAR_T@
#define SIZEOF_UNSIGNED_SHORT @SIZEOF_UNSIGNED_SHORT@
#define SIZEOF_UNSIGNED_INT @SIZEOF_UNSIGNED_INT@
#define SIZEOF_SIZE_T @SIZEOF_SIZE_T@

#cmakedefine WORDS_BIGENDIAN

#define ICONV_CONST @ICONV_CONST@

/* ======================================================================
 * Package info
 * ====================================================================== */

#define SP_PACKAGE "OpenSP"
#define SP_VERSION "1.5.2"
#define SP_MESSAGE_DOMAIN "sp5"
#define PACKAGE "dazzle"
#define VERSION "1.3.3"

/* ======================================================================
 * Paths (substituted by CMake)
 * ====================================================================== */

#ifdef _WIN32
#define SGML_CATALOG_FILES_DEFAULT L"@SGML_CATALOG_FILES_DEFAULT@"
#else
#define SGML_CATALOG_FILES_DEFAULT "@SGML_CATALOG_FILES_DEFAULT@"
#endif
#define SP_LOCALE_DIR "@SP_LOCALE_DIR@"
#define PATH_SEPARATOR '@PATH_SEPARATOR@'

#ifndef DEFAULT_SCHEME_BUILTINS
#define DEFAULT_SCHEME_BUILTINS "builtins.dsl"
#endif

/* ======================================================================
 * Feature flags (set directly by CMake)
 * ====================================================================== */

#cmakedefine SP_MULTI_BYTE 1
#cmakedefine SP_HAVE_SOCKET 1
#if defined(_WIN32) && defined(SP_HAVE_SOCKET)
#define WINSOCK
#endif
#cmakedefine SP_DTDDECL 1
#define SP_DEFINE_TEMPLATES 1

/* ======================================================================
 * MSVC-specific overrides
 * ====================================================================== */

#ifdef _MSC_VER

#undef SP_DEFINE_TEMPLATES

#define SP_INCLUDE_IO_H
#define SP_MSDOS_FILENAMES
#define SP_SHORT_HEADERS

#pragma warning ( disable : 4660 )
#pragma warning ( disable : 4661 )
#pragma warning ( disable : 4786 )
#pragma warning ( disable : 4018 )
#pragma warning ( disable : 4251 )
#pragma warning ( disable : 4275 )
#pragma warning ( disable : 4237 )

#define huge verybig

#define set_new_handler _set_new_handler
#define SP_FANCY_NEW_HANDLER

#define SP_HAVE_BOOL
#define SP_SIZEOF_BOOL_1
#pragma warning ( disable : 4800 )

#define SP_HAVE_PLACEMENT_OPERATOR_DELETE
#define SP_HAVE_TYPENAME
#define SP_HAVE_SETMODE

#define SP_DLLEXPORT __declspec(dllexport)
#define SP_DLLIMPORT __declspec(dllimport)

/* SP_USE_DLL is not defined: we build static libraries */
#define SP_DEFINE_TEMPLATES

#ifdef SP_MULTI_BYTE
#define SP_WIDE_SYSTEM
#endif

#define SP_WCHAR_T_USHORT

#define SP_PCH
/* #undef SP_NO_MESSAGE_TEXT */

#ifdef _MT
#define SP_MUTEX_WIN32
#ifndef SP_ANSI_LIB
#define SP_ANSI_LIB
#endif
#endif

#define SP_NAMESPACE OpenSP
#define SP_ANSI_CLASS_INST

#endif /* _MSC_VER */

/* ======================================================================
 * Derived defines (from autoconf feature detection, for non-MSVC)
 * ====================================================================== */

#ifndef _MSC_VER

#ifdef HAVE_UNISTD_H
#define SP_INCLUDE_UNISTD_H
#endif

#ifdef HAVE_IO_H
#define SP_INCLUDE_IO_H
#endif

#ifdef HAVE_OSFCN_H
#define SP_INCLUDE_OSFCN_H
#endif

#ifndef SP_MSDOS_FILENAMES
#define SP_POSIX_FILENAMES
#endif

#ifdef HAVE_ST_BLKSIZE
#define SP_STAT_BLKSIZE
#endif

#ifdef HAVE_BOOL
#ifndef SP_HAVE_BOOL
#define SP_HAVE_BOOL
#endif
#endif

#ifdef HAVE_TYPENAME
#define SP_HAVE_TYPENAME
#endif

#if (SIZEOF_BOOL == 1)
#define SP_SIZEOF_BOOL_1
#endif

#if (SIZEOF_WCHAR_T == SIZEOF_UNSIGNED_SHORT)
#define SP_WCHAR_T_USHORT
#endif

#ifdef HAVE_NAMESPACES
#define SP_NAMESPACE OpenSP
#endif

#ifdef HAVE_DYNAMIC_CAST
#define SP_HAVE_RTTI
#endif

#ifdef HAVE_INSTANTIATIONS
#ifndef SP_ANSI_CLASS_INST
#define SP_ANSI_CLASS_INST
#endif
#endif

#ifdef HAVE_SETLOCALE
#ifndef SP_HAVE_LOCALE
#define SP_HAVE_LOCALE
#endif
#endif

#if defined(HAVE_GETTEXT) && defined(ENABLE_NLS)
#ifndef SP_HAVE_GETTEXT
#define SP_HAVE_GETTEXT
#endif
#endif

#ifdef WORDS_BIGENDIAN
#define SP_BIG_ENDIAN
#endif

#ifdef HAVE_LIBTHREADS
#define SP_MUTEX_MACH
#endif

#ifdef HAVE_LIBPTHREAD
#define SP_MUTEX_PTHREADS
#endif

#ifdef HAVE_PLACEMENT_OPERATOR_DELETE
#define SP_HAVE_PLACEMENT_OPERATOR_DELETE
#endif

#ifndef HAVE_PLACEMENT_OPERATOR_NEW
#define SP_DECLARE_PLACEMENT_OPERATOR_NEW
#endif

#ifndef HAVE_NAMESPACE_STD
#define SP_NO_STD_NAMESPACE
#endif

#if defined(HAVE_NEW) && defined(HAVE_CASSERT)
#define SP_ANSI_LIB 1
#endif

#ifndef HAVE_MUTABLE
#define mutable
#endif

#endif /* not _MSC_VER */

/* ======================================================================
 * Common derived defines (all platforms)
 * ====================================================================== */

#ifdef SP_HAVE_SETMODE
#ifndef SP_LINE_TERM1
#define SP_LINE_TERM1 '\r'
#define SP_LINE_TERM2 '\n'
#endif
#endif

#ifndef SP_LINE_TERM1
#define SP_LINE_TERM1 '\n'
#endif

#ifndef HAVE_NEW_FOR_SCOPING
#ifndef _MSC_VER
#define for if (0); else for
#endif
#endif

#ifndef SP_HAVE_TYPENAME
#define typename /* as nothing */
#endif

#ifndef SP_DLLEXPORT
#define SP_DLLEXPORT /* as nothing */
#endif

#ifndef SP_DLLIMPORT
#define SP_DLLIMPORT /* as nothing */
#endif

#ifdef SP_USE_DLL
#ifdef BUILD_LIBSP
#define SP_API SP_DLLEXPORT
#else
#define SP_API SP_DLLIMPORT
#endif
#else
#define SP_API /* as nothing */
#endif

#ifdef SP_WIDE_SYSTEM
#ifndef SP_MULTI_BYTE
#define SP_MULTI_BYTE
#endif
#endif

#ifdef SP_NAMESPACE
#define SP_NAMESPACE_SCOPE SP_NAMESPACE::
#else
#define SP_NAMESPACE_SCOPE
#endif

/* ======================================================================
 * Dazzle-specific defines (grove, style)
 * ====================================================================== */

#ifdef SP_NAMESPACE
#ifndef GROVE_NAMESPACE
#define GROVE_NAMESPACE OpenJade_Grove
#endif
#ifndef DSSSL_NAMESPACE
#define DSSSL_NAMESPACE OpenJade_DSSSL
#endif
#endif

#define OPENJADE_PACKAGE "dazzle"
#define OPENJADE_VERSION "1.3.3"
#ifndef OPENJADE_MESSAGE_DOMAIN
#define OPENJADE_MESSAGE_DOMAIN ""
#endif
#ifndef OPENJADE_LOCALE_DIR
#define OPENJADE_LOCALE_DIR ""
#endif

#endif /* not config_INCLUDED */
